export const guitars = [
    {
        name: 'M-14 - Grand Concert Model',
        category: 'Natural Series',
        model_name: 'M-14',
        shape: 'Grand Concert',
        guitar_type: '6-string',
        top: 'AAA cedar',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm(1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm(2.28 inch)',
        neck_thickness: '21mm to 23mm(0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm(2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'none',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'M-14 CP - Grand Concert Model with cutaway and pickup system',
        category: 'Natural Series',
        model_name: 'M-14 CP',
        shape: 'Grand Concert',
        guitar_type: '6-string',
        top: 'AAA Cedar',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (2mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm(1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm(2.28 inch)',
        neck_thickness: '21mm to 23mm(0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm(2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'D-14 - Dreadnought Model',
        category: 'Natural Series',
        model_name: 'D-14',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'none',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'D-14 CP - Dreadnought Model with cutaway and pickup system',
        category: 'Natural Series',
        model_name: 'D-14 CP',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'A-14 CP - Auditorium Model with cutaway and pickup system',
        category: 'Natural Series',
        model_name: 'A-14 CP',
        shape: 'Auditorium',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (2mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '57 mm (2.24 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 12th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '19 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune III nickel',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'J-14 CP - Jumbo Model with cutaway and pickup system',
        category: 'Natural Series',
        model_name: 'J-14 CP',
        shape: 'Jumbo',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (2mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'M-18 - Grand Concert Model',
        category: 'Natural Series',
        model_name: 'M-18',
        shape: 'Grand Concert',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Ovangkol (Style 18)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Pear',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm (2.28 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'none',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'M-18 CP - Grand Concert Model with cutaway and pickup system',
        category: 'Natural Series',
        model_name: 'M-18 CP',
        shape: 'Grand Concert',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Ovangkol (Style 18)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Pear',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (2mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm (2.28 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'D-18 - Dreadnought Model',
        category: 'Natural Series',
        model_name: 'D-18',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Ovangkol (Style 18)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Pear',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'none',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'D-18 - Dreadnought Model',
        category: 'Natural Series',
        model_name: 'D-18 CP',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Ovangkol (Style 18)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Pear',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (2mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'M-31 CP - Grand Concert Model with cutaway and pickup system',
        category: 'Natural Series',
        model_name: 'M-31 CP',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Indian rosewood AA (Style 31)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Mahogany',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (2mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm (2.28 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'D-31 CP - Dreadnought Model with cutaway and pickup system',
        category: 'Natural Series',
        model_name: 'D-31 CP',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Indian rosewood AA (Style 31)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Mahogany',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (2mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'J-14 Baritone - Jumbo Model with pickup system',
        category: 'Natural Series',
        model_name: 'J-14 Baritone',
        shape: 'Jumbo',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '48 mm (1.89 inch)',
        neck_width_at_body_neck_joint: '60 mm (2.36 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '59mm (2.32 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'M-31-12 - Grand Concert Model with pickup system',
        category: 'Natural Series',
        model_name: 'M-31-12',
        shape: 'Grand Concert',
        guitar_type: '12-string',
        top: 'AAA European spruce',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '48 mm (1.89 inch)',
        neck_width_at_body_neck_joint: '60 mm (2.36 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '59mm (2.32 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }
]