export const guitars = [
    {
        name: 'M-14 - Grand Concert Model',
        category: 'naturalSeries',
        model_name: 'M-14',
        shape: 'Grand Concert',
        guitar_type: '6-string',
        top: 'AAA cedar',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm(1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm(2.28 inch)',
        neck_thickness: '21mm to 23mm(0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',

        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm(2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'none',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'M-14 CP - Grand Concert Model with cutaway and pickup system',
        category: 'naturalSeries',
        model_name: 'M-14CP',
        shape: 'Grand Concert',
        guitar_type: '6-string',
        top: 'AAA Cedar',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (2mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm(1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm(2.28 inch)',
        neck_thickness: '21mm to 23mm(0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm(2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'D-14 - Dreadnought Model',
        category: 'naturalSeries',
        model_name: 'D-14',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'none',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'D-14 CP - Dreadnought Model with cutaway and pickup system',
        category: 'naturalSeries',
        model_name: 'D-14CP',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'A-14 CP - Auditorium Model with cutaway and pickup system',
        category: 'naturalSeries',
        model_name: 'A-14CP',
        shape: 'Auditorium',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (2mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '57 mm (2.24 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 12th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '19 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune III nickel',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'J-14 CP - Jumbo Model with cutaway and pickup system',
        category: 'naturalSeries',
        model_name: 'J-14CP',
        shape: 'Jumbo',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (2mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'M-18 - Grand Concert Model',
        category: 'naturalSeries',
        model_name: 'M-18',
        shape: 'Grand Concert',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Ovangkol (Style 18)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Pear',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm (2.28 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'none',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'M-18 CP - Grand Concert Model with cutaway and pickup system',
        category: 'naturalSeries',
        model_name: 'M-18CP',
        shape: 'Grand Concert',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Ovangkol (Style 18)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Pear',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (2mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm (2.28 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'D-18 - Dreadnought Model',
        category: 'naturalSeries',
        model_name: 'D-18',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Ovangkol (Style 18)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Pear',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'none',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'D-18 - Dreadnought Model',
        category: 'naturalSeries',
        model_name: 'D-18CP',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Ovangkol (Style 18)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Pear',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (2mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'M-31 CP - Grand Concert Model with cutaway and pickup system',
        category: 'naturalSeries',
        model_name: 'M-31CP',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Indian rosewood AA (Style 31)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Mahogany',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (2mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm (2.28 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'D-31 CP - Dreadnought Model with cutaway and pickup system',
        category: 'naturalSeries',
        model_name: 'D-31CP',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Indian rosewood AA (Style 31)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Mahogany',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (2mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'J-14 Baritone - Jumbo Model with pickup system',
        category: 'naturalSeries',
        model_name: 'J-14Baritone',
        shape: 'Jumbo',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '48 mm (1.89 inch)',
        neck_width_at_body_neck_joint: '60 mm (2.36 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '59mm (2.32 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'M-31-12 - Grand Concert Model with pickup system',
        category: 'naturalSeries',
        model_name: 'M-31-12',
        shape: 'Grand Concert',
        guitar_type: '12-string',
        top: 'AAA European spruce',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '48 mm (1.89 inch)',
        neck_width_at_body_neck_joint: '60 mm (2.36 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '59mm (2.32 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open - pored satin gloss(natural finish)',
        neck_finish: 'Open - pored satin gloss(natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'M-32 - Grand Concert Model',
        category: 'deluxeSeries',
        model_name: 'M-32',
        shape: 'Grand Concert',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Indian rosewood AAA (Style 32)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Wood core with abalone purfling',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Indian rosewood',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm (2.28 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I gold',
        tuner_buttons: 'Ebony',
        body_finish: 'High-gloss finish',
        neck_finish: 'Satin-gloss, filled grain',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'M-32 CP - Grand Concert Model with cutaway and pickup system',
        category: 'deluxeSeries',
        model_name: 'M-32CP',
        shape: 'Grand Concert',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Indian rosewood AAA (Style 32)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wood core with abalone purfling',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Indian rosewood',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Snowflakes 3-19th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm (2.28 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I gold',
        tuner_buttons: 'Ebony',
        body_finish: 'High-gloss finish',
        neck_finish: 'Satin-gloss, filled grain',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'D-32 - Dreadnought Model',
        category: 'deluxeSeries',
        model_name: 'D-32',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Indian rosewood AAA (Style 32)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Wood core with abalone purfling',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Indian rosewood',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I gold',
        tuner_buttons: 'Ebony',
        body_finish: 'High-gloss finish',
        neck_finish: 'Satin-gloss, filled grain',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'D-32 CP - Dreadnought Model with cutaway and pickup system',
        category: 'deluxeSeries',
        model_name: 'D-32-CP',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Indian rosewood AAA (Style 32)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wood core with abalone purfling',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Indian rosewood',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Snowflakes 3-19th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I gold',
        tuner_buttons: 'Ebony',
        body_finish: 'High-gloss finish',
        neck_finish: 'Satin-gloss, filled grain',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'A-32 CP - Auditorium Model with cutaway and pickup system',
        category: 'deluxeSeries',
        model_name: 'A-32CP',
        shape: 'Auditorium',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Indian rosewood AAA (Style 32)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wood core with abalone purfling',
        headstock: 'Slotted headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Indian rosewood',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Snowflakes 3-19th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '57 mm (2.24 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 12th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I gold',
        tuner_buttons: 'Ebony',
        body_finish: 'High-gloss finish',
        neck_finish: 'Satin-gloss, filled grain',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'J-32 CP - Jumbo Model with cutaway and pickup system',
        category: 'deluxeSeries',
        model_name: 'J-32CP',
        shape: 'Jumbo',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Indian rosewood AAA (Style 32)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Wood core with abalone purfling',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Indian rosewood',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Snowflakes 3-19th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm(25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I gold',
        tuner_buttons: 'Ebony',
        body_finish: 'High-gloss finish',
        neck_finish: 'Satin-gloss, filled grain',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'J-32 Baritone - Jumbo Model with pickup system',
        category: 'deluxeSeries',
        model_name: 'J-32Baritone',
        shape: 'Jumbo',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Indian rosewood AAA (Style 32)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wood core with abalone purfling',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Indian rosewood',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'none',
        fingerboard_inlays: 'Snowflakes 3-19th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '48 mm (1.89 inch)',
        neck_width_at_body_neck_joint: '60 mm (2.36 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '680 mm (26.8 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '59mm (2.32 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I gold',
        tuner_buttons: 'Ebony',
        body_finish: 'High-gloss finish',
        neck_finish: 'Satin-gloss, filled grain',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'M-35 CP - Grand Concert Model with cutaway and pickup system',
        category: 'deluxeSeries',
        model_name: 'J-32Baritone',
        shape: 'Grand Concert',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Oak (Style 35)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wood core with abalone purfling',
        headstock: 'Flat headstock',
        headstock_veneer: 'Ebony',
        body_bindings: 'Mahogany',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Snowflakes 3-19th fret',
        heel_cap: 'Ebony',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm (2.28 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm (25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I gold',
        tuner_buttons: 'Ebony',
        body_finish: 'High-gloss finish',
        neck_finish: 'Satin-gloss, filled grain',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'D-35 CP - Dreadnought Model with cutaway and pickup system',
        category: 'deluxeSeries',
        model_name: 'D-35CP',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Oak (Style 35)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wood core with abalone purfling',
        headstock: 'Flat headstock',
        headstock_veneer: 'Ebony',
        body_bindings: 'Mahogany',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Snowflakes 3-19th fret',
        heel_cap: 'Ebony',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm (25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I gold',
        tuner_buttons: 'Ebony',
        body_finish: 'High-gloss finish',
        neck_finish: 'Satin-gloss, filled grain',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'A-36 Premium - Auditorium Model with pickup system',
        category: 'premiumSeries',
        model_name: 'A-36Premium',
        shape: 'Auditorium',
        guitar_type: '6-string',
        top: 'AAAA European spruce',
        back_sides: 'Cypress (Style 36)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Premium Design with two woods and abalone purfling',
        headstock: 'Slotted headstock',
        headstock_veneer: 'Ebony (high-gloss polished)',
        body_bindings: 'Indian rosewood',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Ebony',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '57 mm (2.24 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 12th fret',
        scale_length: '650 mm (25.6 inch)',
        frets: '19 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune III gold',
        tuner_buttons: 'Galalith',
        body_finish: 'High-gloss finish',
        neck_finish: 'Satin-gloss, filled grain',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'M-52 Premium - Grand Concert Model with pickup system',
        category: 'premiumSeries',
        model_name: 'M-52Premium',
        shape: 'Grand Concert',
        guitar_type: '6-string',
        top: 'AAAA European spruce',
        back_sides: 'Myrtle (Style 52)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Premium Design with two woods and abalone purfling',
        headstock: 'Flat headstock',
        headstock_veneer: 'Ebony (high-gloss polished)',
        body_bindings: 'Mahogany',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Ebony',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm (2.28 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm (25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Bone with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune II gold',
        tuner_buttons: 'Galalith',
        body_finish: 'High-gloss finish',
        neck_finish: 'Satin-gloss, filled grain',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'D-53 Premium - Dreadnought Model with pickup system',
        category: 'premiumSeries',
        model_name: 'D-53Premium',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAAA European spruce',
        back_sides: 'Cocobolo (Style 53)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Premium Design with two woods and abalone purfling',
        headstock: 'Flat headstock',
        headstock_veneer: 'Ebony (high-gloss polished)',
        body_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Ebony',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm (25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Bone with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune II gold',
        tuner_buttons: 'Galalith',
        body_finish: 'High-gloss finish',
        neck_finish: 'Satin-gloss, filled grain',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'J-50 Premium - Jumbo Model with pickup system',
        category: 'premiumSeries',
        model_name: 'J-50Premium',
        shape: 'Jumbo',
        guitar_type: '6-string',
        top: 'AAAA European spruce',
        back_sides: 'Flamed maple (Style 50)',
        neck: 'Flamed maple',
        cutaway: 'none',
        soundhole_rosette: 'Premium Design with two woods and abalone purfling',
        headstock: 'Flat headstock',
        headstock_veneer: 'Ebony (high-gloss polished)',
        body_bindings: 'Snakewood',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Ebony',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm (25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Bone with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune II gold',
        tuner_buttons: 'Galalith',
        body_finish: 'High-gloss finish',
        neck_finish: 'Satin-gloss, filled grain',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'Ulli Bögershausen Signature - Grand Concert Model with cutaway and pickup system',
        category: 'signatureSeries',
        model_name: 'Ulli_Bögershausen_Signature',
        shape: 'Grand Concert',
        guitar_type: '6-string',
        top: 'AAAA European spruce',
        back_sides: 'Ziricote (Style 45)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Premium Design with two woods and abalone purfling',
        headstock: 'Flat headstock',
        headstock_veneer: 'Matching wood of back & sides (Ziricote)',
        body_bindings: 'Muninga',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'none',
        heel_cap: 'Matching wood of back & sides (Ziricote)',
        nut: 'Bone',
        neck_width_a_nut: '46 mm (1.81 inch)',
        neck_width_at_body_neck_joint: '58 mm (2.28 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm (25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '57mm (2.24 inch)',
        bridge_pins: 'Bone with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I gold',
        tuner_buttons: 'Ebony',
        body_finish: 'Open-pored satin gloss (natural finish) Filled-grain finished waist (treble side) for guitar rest',
        neck_finish: 'Open-pored satin gloss (natural finish)',
        second_strap_button: 'Like end pin, normal position',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'Sungha Jung Signature - Grand Concert Model with cutaway and pickup system',
        category: 'signatureSeries',
        model_name: 'Sungha_Jung_Signature',
        shape: 'Grand Concert',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Indian rosewood AAA (Style 32)',
        neck: 'Mahogany',
        cutaway: 'soft (round)',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        headstock_bindings: 'Maple',
        fingerboard_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Sungha Jung signature inlay',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'C - shape(formerly D round)',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm (25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Rosewood',
        body_finish: 'Open-pored satin gloss (natural finish)',
        neck_finish: 'Open-pored satin gloss (natural finish)',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        second_strap_button: 'Like end pin, normal position',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }, {
        name: 'Gregor Meyle Signature - Dreadnought Model with pickup system',
        category: 'signatureSeries',
        model_name: 'Gregor_Meyle_Signature',
        shape: 'Dreadnought',
        guitar_type: '6-string',
        top: 'AAA European spruce',
        back_sides: 'Mahogany (Style 14)',
        neck: 'Mahogany',
        cutaway: 'none',
        soundhole_rosette: 'Wooden core with purflings',
        headstock: 'Flat headstock',
        headstock_veneer: 'Indian rosewood',
        body_bindings: 'Maple',
        headstock_bindings: 'Maple',
        fingerboard_bindings: 'Maple',
        body_purfling: 'Purfling from noble woods',
        fingerboard: 'Ebony',
        headstock_inlays: 'White MOP Lakewood logo',
        fingerboard_inlays: 'Dots (5mm) 3-17th fret',
        heel_cap: 'Indian rosewood',
        nut: 'Bone',
        neck_width_a_nut: '44 mm (1.73 inch)',
        neck_width_at_body_neck_joint: '56 mm (2.20 inch)',
        neck_thickness: '21mm to 23mm (0.83 to 0.91 inch)',
        neck_profile: 'V-shape',
        body_neck_joint: 'at 14th fret',
        scale_length: '650 mm (25.6 inch)',
        frets: '20 frets',
        bridge: 'Ebony',
        saddle: 'Bone',
        string_spacing_at_bridge: '55mm (2.17 inch)',
        bridge_pins: 'Ebony with pearl dot',
        pickup_system: 'L.R. Baggs Anthem',
        tuners: 'Lakewood ProTune I chrome',
        tuner_buttons: 'Chrome',
        body_finish: 'High-gloss finish',
        neck_finish: 'Satin-gloss, filled grain',
        colors_dyes_body: 'Wine, translucent',
        colors_dyes_on_neck: 'Wine, translucent',
        end_pin: 'Lakewood end pin(matching bridge pins)',
        second_strap_button: 'Like end pin, normal position',
        strings: 'Elixir Nanoweb Phosphorbronze .012 - .053(light)',
        case: 'Hiscox Lakewood hard case'
    }
]

export default guitars